### ISSUE TITLE
Medoids being relocated to another cluster

### ISSUE THREAD

**Issue by CaioMelo8** [gustavoaires/senttext#6] opened 2017-12-02 21:30 UTC
When executing the clustering method in the K-medoids class, the for that iteracts through all the documents passed to the clusters, including those that have already been randomly assigned to be a cluster's medoid.

As such, the algorithm calculates again the distance between the document and all the assigned medoids, and assigns it to a cluster with the closest or least distant medoid. 
That wouldn't be a problem, as the medoid would be the "closest medoid to itself". But, when there's a case when two different medoids are exactly the same, that can become an issue. In fact, it would become a matter of in which order their distances are calculated.

Consider the example:

### Medoids
[1] {id: 10, text: 'example text', cluster: 3}
[2] {id: 98, text: 'example text', cluster: 5}

Consider you're currently deciding to which cluster you'll assign the medoid [2] as a document, as it is part of the documents collection. 

When calculating the distance from the document {id:98, text: 'example text', cluster: 5}, that is also a medoid, to the first medoid {id:10, text: 'example text', cluster: 3} in the medoids list, the distance value would be 0. So, as the algorithm goes, even if the distance from the document to the medoid [2] (that is, to itself) is also 0, the medoid [1] would still be considered the closest medoid, as the distance to the medoid [2] isn't smaller.

That way, the document would be assigned to the cluster number 3, that is, the cluster fro the document [1]. Furthermore, the document would still be a medoid,  but already in cluster. That way, no other document would be assigned to the cluster 5, making it empty.

This is a matter of order, to such extend that there could be cases in which no medoids would be relocated to another clusters. Still, it can cause problems.

**Comment by gustavoaires** [comment] 2017-12-03 14:15
This is a major problem. It can impact the result completely. I merged your PR. How is execution time now? I think this can make it shorter.

**Comment by CaioMelo8** [comment] 2017-12-03 14:47
Execution time varies greatly depending on which distance algorithm you are using.

I haven't recorded data on it, but in my dataset, with something about 2000 documents:

- **Using Jaccard distance:** it takes a few seconds to complete a single execution.
- **Using Levenshtein distance:** it takes about half a minute to complete a single execution.

When executing with the a dataset of around 4000 documents, but considering different K values and implementing many iterations to each one of them, the difference becomes way more discrepant.

- **In the case of Jaccard**, using a range of K values between 3 and 80, and considering 40 iteractions to each K value, the completion time ranges from 3 to 5 minutes
- **In the case of Levenshtein**, however, using a range of K values between 3 and 30, and considering 20 iteractions to each K value, the completion time is longer than 3 hours.

**Comment by gustavoaires** [comment] 2017-12-03 21:18
I have notice that. The problem is the way you have to calculate Levenshtein distance. It has to look to every single character in your document, generating a matrix. This is not as fast as just looking to the common words between the source and target document. I'll close the issue now.

**Closed as completed** 2017-12-03 21:19 UTC
Labels: bug
